services:
  db:
    image: postgres:18.0
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_DB: ${POSTGRESQL_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${POSTGRESQL_USERNAME}"]
      interval: 10s
      timeout: 5s
      retries: 5

  backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: naujava-backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://db:5432/${POSTGRESQL_DB:-testing_system}
      - SPRING_DATASOURCE_USERNAME=${POSTGRESQL_USERNAME:-postgres}
      - SPRING_DATASOURCE_PASSWORD=${POSTGRESQL_PASSWORD}
      - SECURITY_ORIGIN_FRONTED=${SECURITY_ORIGIN_FRONTED:-http://localhost:5173}
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build:
      context: ./frontend/testing-system
      dockerfile: Dockerfile
    container_name: testing-system-frontend
    environment:
      - VITE_BACKEND_API_URL=${VITE_BACKEND_API_URL:-http://localhost:8080}
    volumes:
      - ./frontend/testing-system/src:/app/src
      - ./frontend/testing-system/public:/app/public
      - ./frontend/testing-system/index.html:/app/index.html
      - ./frontend/testing-system/vite.config.js:/app/vite.config.js
      - /app/node_modules
    stdin_open: true
    tty: true

  nginx:
    image: nginx:alpine
    container_name: nginx-proxy
    ports:
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - frontend
    extra_hosts:
      - "host.docker.internal:host-gateway"

volumes:
  postgres-data:
