version: '3.8'

services:
  db:
    image: postgres:18.0
    container_name: postgres_db
    environment:
      POSTGRES_PASSWORD: ${POSTGRESQL_PASSWORD}
      POSTGRES_USER: ${POSTGRESQL_USERNAME}
      POSTGRES_DB: ${POSTGRESQL_DB}
    ports:
      - "5433:5432"
    volumes:
      - postgres-data:/var/lib/postgresql
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "${POSTGRESQL_USERNAME}" ]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  postgres-data: